name       : haskell-memory
version    : 0.14.1
release    : 1
source     :
    - http://hackage.haskell.org/package/memory-0.14.1/memory-0.14.1.tar.gz : 1cd87a34ca28ab5fbb9fbeb82f66cdbabf4e276e10caf7a64b798bf42edc0825
license    : BSD-3-Clause
component  : programming.haskell
summary    : Chunk of memory, polymorphic byte array management and manipulation
description: |
    Chunk of memory, polymorphic byte array management and manipulation
builddeps  :
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
