name       : haskell-memory
version    : 0.14.16
release    : 2
source     :
    - https://hackage.haskell.org/package/memory-0.14.16/memory-0.14.16.tar.gz : 7bb0834ab28ce1248f3be09df211d49d20d703cdcda3ed16cde99356e2d72b0f
license    : BSD-3-Clause
component  : programming.haskell
summary    : Chunk of memory, polymorphic byte array management and manipulation
description: |
    Chunk of memory, polymorphic byte array management and manipulation
builddeps  :
    - ghc
    - haskell-cabal-install
    - haskell-foundation
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
